services:
  postgres:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      app_network:
        aliases:
          - sql_server
    volumes:
      - url-shortener-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 10
  app:
    depends_on:
      postgres:
        condition: service_healthy
    build: ./src
    env_file:
      - .env
    networks:
        app_network:
          aliases:
            - app_server
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4242/ || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 10
  nginx:
      build: ./nginx
      ports:
        - 80:7777
        - 443:443
      volumes:
        - certbot-etc:/etc/letsencrypt
        - certbot-www:/var/www/certbot
      networks:
        app_network:
          aliases:
            - nginx_server
      depends_on:
        app:
          condition: service_healthy
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    

networks:
  app_network:

volumes:
  url-shortener-db:
  certbot-etc:
  certbot-www: