services:
  postgres:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      app_network:
        aliases:
          - sql_server
    volumes:
      - url-shortener-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 10
  app:
    depends_on:
      postgres:
        condition: service_healthy
    build: ./src
    ports:
      - 127.0.0.1:4242:4242
    env_file:
      - .env
    networks:
        app_network:
          aliases:
            - app_server
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4242/ || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 10
  nginx:
      build: ./nginx
      ports:
      - 127.0.0.1:80:80
      networks:
        app_network:
          aliases:
            - nginx_server
      depends_on:
        app:
          condition: service_healthy
networks:
  app_network:

volumes:
  url-shortener-db: